name: nutriplato
description: Aprende a crear tu plato del Bien Comer y cuidarte en el dia a dia.
publish_to: 'none'
version: 3.0.0+4

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  android_intent_plus: ^5.3.0
  circular_countdown_timer: ^0.2.3
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.4.0
  get: ^4.6.6
  google_fonts: ^6.2.1
  http: ^1.2.1
  icons_plus: ^5.0.0
  intl: ^0.20.2
  introduction_screen: ^3.1.8
  percent_indicator: ^4.2.4
  provider: ^6.0.5
  salomon_bottom_bar: ^3.3.2
  shared_preferences: ^2.1.1
  showcaseview: ^4.0.1
  share_plus: ^10.1.1
  shimmer: ^3.0.0
  lottie: ^3.1.2
  smooth_page_indicator: ^1.1.0

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "lib/data/img/logo_nutriplato.png"

flutter:
  uses-material-design: true
  assets:
    - lib/data/img/
    - lib/data/img/porciones_mano/
    - lib/data/img/animal/
    - lib/data/img/cereales/
    - lib/data/img/fruits/
    - lib/data/img/leguminosas/
    - lib/data/img/vegetables/
