import 'package:flutter/material.dart';
import 'package:font_awesome_flutter/font_awesome_flutter.dart';
import 'package:nutriplato/fitness/exercise/exercise.model.dart';
import 'package:nutriplato/fitness/fitness.model.dart';

final exercisesData = [
  Fitness(
    name: 'Novato',
    description: 'Ejercicio basico para principiantes.',
    difficulty: 'Facil',
    tags: ['Pierna', 'Hombro', 'Accesible'],
    sets: 1,
    rest: 15,
    exercises: [
      Exercise(name: 'Sentadilla', description: '', quantity: 5, images: []),
      Exercise(
          name: 'Desplazamientos', description: '', quantity: 10, images: []),
      Exercise(
          name: 'Levantamiento de pantorrillas',
          description: '',
          quantity: 5,
          images: []),
      Exercise(
          name: 'Tijera de brazos', description: '', quantity: 10, images: []),
      Exercise(
          name: 'Tijera de hombros', description: '', quantity: 10, images: []),
      Exercise(
          name: 'Extension de biceps',
          description: '',
          quantity: 10,
          images: []),
      Exercise(
          name: 'Rodilla al codo', description: '', quantity: 10, images: []),
    ],
    icon: FontAwesomeIcons.dumbbell,
  ),
  Fitness(
    name: 'HIIT principiante',
    description: 'Entrenamiento para fortalecer el corazon.',
    difficulty: 'Facil',
    tags: ['HIIT', 'Accesible', 'Cuerpo Completo'],
    sets: 1,
    rest: 10,
    gradients: [
      Colors.indigo,
      Colors.blue,
    ],
    exercises: [
      Exercise(
        name: 'Marcha en el lugar',
        description: '',
        images: [],
        time: 15,
      ),
      Exercise(
        name: 'Levantamiento de rodillas',
        description: '',
        images: [],
        time: 15,
      ),
      Exercise(
        name: 'Circulos con hombros',
        description: '',
        images: [],
        time: 15,
      ),
      Exercise(
        name: 'Levantamiento de rodillas',
        description: '',
        images: [],
        time: 15,
      ),
      Exercise(
        name: 'Extencion de Biceps',
        description: '',
        images: [],
        time: 15,
      ),
      Exercise(
        name: 'Levantamiento de rodillas',
        description: '',
        images: [],
        time: 15,
      ),
    ],
    icon: FontAwesomeIcons.personRunning,
  ),
  Fitness(
      name: 'Abdominales sencillas',
      description: '',
      difficulty: 'Facil',
      tags: ['Core', 'Abdomen', 'Accesible'],
      sets: 0,
      rest: 10,
      exercises: [
        Exercise(
          name: 'Crunches',
          description: '',
          quantity: 10,
          images: [],
        ),
        Exercise(
          name: 'Bicicletas',
          description: '',
          images: [],
          quantity: 10,
        ),
        Exercise(
          name: 'Giros sentado',
          description: '',
          images: [],
          quantity: 10,
        ),
        Exercise(
          name: 'Levantamiento de piernas',
          description: '',
          images: [],
          quantity: 10,
        ),
        Exercise(
          name: 'Plancha',
          description: '',
          images: [],
          time: 10,
        ),
        Exercise(
          name: 'Elevacion de piernas en plancha',
          description: '',
          images: [],
          quantity: 10,
        ),
      ],
      icon: FontAwesomeIcons.heartPulse),
  Fitness(
    name: 'Abdominales sencillas II',
    description: '',
    difficulty: 'Facil',
    tags: ['Core', 'Abdomen', 'Accesible'],
    sets: 0,
    rest: 5,
    exercises: [
      Exercise(
        name: 'Crunches',
        description: '',
        quantity: 12,
        images: [],
      ),
      Exercise(
        name: 'Bicicletas',
        description: '',
        images: [],
        quantity: 12,
      ),
      Exercise(
        name: 'Giros sentado',
        description: '',
        images: [],
        quantity: 12,
      ),
      Exercise(
        name: 'Levantamiento de piernas',
        description: '',
        images: [],
        quantity: 15,
      ),
      Exercise(
        name: 'Plancha',
        description: '',
        images: [],
        time: 20,
      ),
      Exercise(
        name: 'Elevacion de piernas en plancha',
        description: '',
        images: [],
        quantity: 12,
      ),
    ],
    icon: FontAwesomeIcons.heartPulse,
  ),
  // NUEVAS RUTINAS DE EJERCICIO
  Fitness(
    name: 'Cardio Quema Grasa',
    description:
        'Rutina cardiovascular de alta intensidad para quemar calorías.',
    difficulty: 'Intermedio',
    tags: ['Cardio', 'Quema grasa', 'Cuerpo Completo'],
    sets: 2,
    rest: 30,
    gradients: [
      Colors.orange,
      Colors.red,
    ],
    exercises: [
      Exercise(
        name: 'Jumping Jacks',
        description: 'Saltos abriendo brazos y piernas simultáneamente',
        images: [],
        time: 30,
      ),
      Exercise(
        name: 'Rodillas altas',
        description: 'Correr en el lugar elevando las rodillas al pecho',
        images: [],
        time: 30,
      ),
      Exercise(
        name: 'Burpees',
        description: 'Desde parado, baja a plancha, sube y salta',
        images: [],
        quantity: 10,
      ),
      Exercise(
        name: 'Escaladores',
        description: 'En posición de plancha, alterna las rodillas al pecho',
        images: [],
        time: 30,
      ),
      Exercise(
        name: 'Sentadilla con salto',
        description: 'Sentadilla normal terminando con un salto',
        images: [],
        quantity: 12,
      ),
      Exercise(
        name: 'Patadas al frente',
        description: 'Alterna patadas frontales a la altura de la cadera',
        images: [],
        time: 30,
      ),
    ],
    icon: FontAwesomeIcons.fire,
  ),
  Fitness(
    name: 'Fuerza de Piernas',
    description: 'Fortalece cuádriceps, glúteos y pantorrillas.',
    difficulty: 'Intermedio',
    tags: ['Piernas', 'Glúteos', 'Fuerza'],
    sets: 3,
    rest: 45,
    gradients: [
      Colors.green,
      Colors.teal,
    ],
    exercises: [
      Exercise(
        name: 'Sentadillas',
        description: 'Baja como si te sentaras, mantén la espalda recta',
        images: [],
        quantity: 15,
      ),
      Exercise(
        name: 'Zancadas alternadas',
        description: 'Da un paso largo al frente y baja la rodilla trasera',
        images: [],
        quantity: 12,
      ),
      Exercise(
        name: 'Puente de glúteos',
        description: 'Acostado boca arriba, eleva la cadera apretando glúteos',
        images: [],
        quantity: 15,
      ),
      Exercise(
        name: 'Sentadilla sumo',
        description: 'Sentadilla con piernas muy abiertas y pies hacia afuera',
        images: [],
        quantity: 12,
      ),
      Exercise(
        name: 'Elevación de pantorrillas',
        description: 'Ponte de puntas y baja lentamente',
        images: [],
        quantity: 20,
      ),
      Exercise(
        name: 'Sentadilla isométrica en pared',
        description: 'Apoya la espalda en la pared, rodillas a 90 grados',
        images: [],
        time: 30,
      ),
      Exercise(
        name: 'Patada de glúteo',
        description: 'En 4 puntos, eleva una pierna hacia atrás',
        images: [],
        quantity: 15,
      ),
    ],
    icon: FontAwesomeIcons.personWalking,
  ),
  Fitness(
    name: 'Brazos y Hombros',
    description: 'Tonifica y fortalece la parte superior del cuerpo sin pesas.',
    difficulty: 'Intermedio',
    tags: ['Brazos', 'Hombros', 'Pecho'],
    sets: 3,
    rest: 40,
    gradients: [
      Colors.purple,
      Colors.deepPurple,
    ],
    exercises: [
      Exercise(
        name: 'Lagartijas clásicas',
        description: 'Flexión de brazos manteniendo el cuerpo recto',
        images: [],
        quantity: 10,
      ),
      Exercise(
        name: 'Lagartijas diamante',
        description: 'Manos juntas formando un diamante bajo el pecho',
        images: [],
        quantity: 8,
      ),
      Exercise(
        name: 'Fondos en silla',
        description: 'Apoya las manos en una silla y baja el cuerpo',
        images: [],
        quantity: 12,
      ),
      Exercise(
        name: 'Plancha con toque de hombro',
        description: 'En plancha, toca el hombro opuesto alternando',
        images: [],
        quantity: 16,
      ),
      Exercise(
        name: 'Círculos de brazos',
        description: 'Brazos extendidos, hacer círculos pequeños',
        images: [],
        time: 30,
      ),
      Exercise(
        name: 'Comando (plancha a lagartija)',
        description: 'Alterna entre plancha de antebrazos y plancha alta',
        images: [],
        quantity: 10,
      ),
      Exercise(
        name: 'Flexión de superman',
        description: 'Boca abajo, eleva brazos y piernas del suelo',
        images: [],
        quantity: 12,
      ),
    ],
    icon: FontAwesomeIcons.handFist,
  ),
  Fitness(
    name: 'Core de Acero',
    description: 'Rutina intensiva para fortalecer todo el core.',
    difficulty: 'Avanzado',
    tags: ['Core', 'Abdomen', 'Espalda'],
    sets: 3,
    rest: 30,
    gradients: [
      Colors.amber,
      Colors.orange,
    ],
    exercises: [
      Exercise(
        name: 'Plancha frontal',
        description: 'Mantén el cuerpo recto apoyado en antebrazos',
        images: [],
        time: 45,
      ),
      Exercise(
        name: 'Plancha lateral derecha',
        description: 'Apoya antebrazo derecho, cuerpo de lado',
        images: [],
        time: 30,
      ),
      Exercise(
        name: 'Plancha lateral izquierda',
        description: 'Apoya antebrazo izquierdo, cuerpo de lado',
        images: [],
        time: 30,
      ),
      Exercise(
        name: 'V-ups',
        description: 'Acostado, eleva piernas y torso simultáneamente',
        images: [],
        quantity: 12,
      ),
      Exercise(
        name: 'Bicicleta aérea',
        description: 'Simula pedalear acostado boca arriba',
        images: [],
        quantity: 20,
      ),
      Exercise(
        name: 'Escaladores lentos',
        description: 'Escaladores con movimiento controlado',
        images: [],
        quantity: 16,
      ),
      Exercise(
        name: 'Dead bug',
        description: 'Boca arriba, alterna brazo y pierna opuestos',
        images: [],
        quantity: 14,
      ),
      Exercise(
        name: 'Plancha con rotación',
        description: 'En plancha, gira abriendo un brazo al techo',
        images: [],
        quantity: 10,
      ),
    ],
    icon: FontAwesomeIcons.shieldHalved,
  ),
  Fitness(
    name: 'Yoga para Principiantes',
    description: 'Secuencia suave para mejorar flexibilidad y relajación.',
    difficulty: 'Facil',
    tags: ['Yoga', 'Flexibilidad', 'Relajación'],
    sets: 1,
    rest: 10,
    gradients: [
      Colors.cyan,
      Colors.lightBlue,
    ],
    exercises: [
      Exercise(
        name: 'Postura del niño',
        description: 'Arrodillado, estira los brazos al frente y relaja',
        images: [],
        time: 60,
      ),
      Exercise(
        name: 'Gato-Vaca',
        description: 'En 4 puntos, alterna arquear y redondear la espalda',
        images: [],
        quantity: 10,
      ),
      Exercise(
        name: 'Perro boca abajo',
        description: 'Forma una V invertida con el cuerpo',
        images: [],
        time: 45,
      ),
      Exercise(
        name: 'Guerrero I',
        description: 'Zancada larga, brazos arriba, mira al frente',
        images: [],
        time: 30,
      ),
      Exercise(
        name: 'Guerrero II',
        description: 'Zancada lateral, brazos extendidos a los lados',
        images: [],
        time: 30,
      ),
      Exercise(
        name: 'Postura del árbol',
        description: 'Equilibrio en una pierna, pie en el muslo contrario',
        images: [],
        time: 30,
      ),
      Exercise(
        name: 'Torsión sentado',
        description: 'Sentado, gira el torso hacia un lado',
        images: [],
        time: 30,
      ),
      Exercise(
        name: 'Savasana (relajación)',
        description: 'Acuéstate boca arriba, relaja todo el cuerpo',
        images: [],
        time: 120,
      ),
    ],
    icon: FontAwesomeIcons.spa,
  ),
  Fitness(
    name: 'Estiramiento Completo',
    description: 'Rutina de estiramientos para después del ejercicio.',
    difficulty: 'Facil',
    tags: ['Estiramiento', 'Recuperación', 'Flexibilidad'],
    sets: 1,
    rest: 5,
    gradients: [
      Colors.pink,
      Colors.pinkAccent,
    ],
    exercises: [
      Exercise(
        name: 'Estiramiento de cuello',
        description: 'Inclina la cabeza a cada lado suavemente',
        images: [],
        time: 30,
      ),
      Exercise(
        name: 'Estiramiento de hombros',
        description: 'Cruza un brazo sobre el pecho y sostén',
        images: [],
        time: 30,
      ),
      Exercise(
        name: 'Estiramiento de tríceps',
        description: 'Brazo atrás de la cabeza, empuja el codo',
        images: [],
        time: 30,
      ),
      Exercise(
        name: 'Estiramiento de espalda',
        description: 'Abraza tus rodillas hacia el pecho acostado',
        images: [],
        time: 45,
      ),
      Exercise(
        name: 'Estiramiento de cuádriceps',
        description: 'De pie, lleva el talón al glúteo',
        images: [],
        time: 30,
      ),
      Exercise(
        name: 'Estiramiento de isquiotibiales',
        description: 'Sentado, alcanza los dedos de los pies',
        images: [],
        time: 45,
      ),
      Exercise(
        name: 'Estiramiento de cadera',
        description: 'Posición de paloma o figura 4 acostado',
        images: [],
        time: 45,
      ),
      Exercise(
        name: 'Estiramiento de pantorrillas',
        description: 'Apoya el pie contra la pared e inclínate',
        images: [],
        time: 30,
      ),
    ],
    icon: FontAwesomeIcons.child,
  ),
  Fitness(
    name: 'HIIT Avanzado',
    description: 'Entrenamiento de alta intensidad para deportistas.',
    difficulty: 'Avanzado',
    tags: ['HIIT', 'Cardio', 'Avanzado'],
    sets: 4,
    rest: 20,
    gradients: [
      Colors.red,
      Colors.deepOrange,
    ],
    exercises: [
      Exercise(
        name: 'Burpees con salto',
        description: 'Burpee completo terminando con salto explosivo',
        images: [],
        quantity: 12,
      ),
      Exercise(
        name: 'Sprints en el lugar',
        description: 'Corre lo más rápido posible sin moverte',
        images: [],
        time: 20,
      ),
      Exercise(
        name: 'Saltos de caja (step)',
        description: 'Sube y baja de una superficie elevada saltando',
        images: [],
        quantity: 15,
      ),
      Exercise(
        name: 'Sentadilla con salto 180',
        description: 'Sentadilla saltando y girando 180 grados',
        images: [],
        quantity: 10,
      ),
      Exercise(
        name: 'Plancha con saltos',
        description: 'En plancha, salta abriendo y cerrando piernas',
        images: [],
        quantity: 15,
      ),
      Exercise(
        name: 'Escaladores explosivos',
        description: 'Escaladores a máxima velocidad',
        images: [],
        time: 20,
      ),
    ],
    icon: FontAwesomeIcons.bolt,
  ),
  Fitness(
    name: 'Entrenamiento Funcional',
    description: 'Movimientos que mejoran tu rendimiento en la vida diaria.',
    difficulty: 'Intermedio',
    tags: ['Funcional', 'Cuerpo Completo', 'Equilibrio'],
    sets: 3,
    rest: 40,
    gradients: [
      Colors.blueGrey,
      Colors.grey,
    ],
    exercises: [
      Exercise(
        name: 'Sentadilla con press',
        description: 'Sentadilla subiendo los brazos al levantarte',
        images: [],
        quantity: 12,
      ),
      Exercise(
        name: 'Zancada con rotación',
        description: 'Zancada girando el torso hacia la pierna adelantada',
        images: [],
        quantity: 10,
      ),
      Exercise(
        name: 'Peso muerto a una pierna',
        description: 'Inclínate hacia adelante levantando una pierna atrás',
        images: [],
        quantity: 10,
      ),
      Exercise(
        name: 'Plancha con remada',
        description: 'En plancha, simula jalar un peso hacia el costado',
        images: [],
        quantity: 12,
      ),
      Exercise(
        name: 'Salto lateral',
        description: 'Salta de lado a lado manteniendo equilibrio',
        images: [],
        quantity: 16,
      ),
      Exercise(
        name: 'Inchworm',
        description: 'Camina con las manos hasta plancha y regresa',
        images: [],
        quantity: 8,
      ),
      Exercise(
        name: 'Turkish get-up simplificado',
        description: 'Levántate del suelo sin usar las manos',
        images: [],
        quantity: 6,
      ),
    ],
    icon: FontAwesomeIcons.personArrowUpFromLine,
  ),
  Fitness(
    name: 'Rutina para Oficina',
    description: 'Ejercicios que puedes hacer en tu escritorio.',
    difficulty: 'Facil',
    tags: ['Oficina', 'Escritorio', 'Postura'],
    sets: 1,
    rest: 10,
    gradients: [
      Colors.brown,
      Colors.blueGrey,
    ],
    exercises: [
      Exercise(
        name: 'Rotación de cuello',
        description: 'Gira suavemente el cuello en círculos',
        images: [],
        time: 30,
      ),
      Exercise(
        name: 'Encogimiento de hombros',
        description: 'Sube los hombros a las orejas y suelta',
        images: [],
        quantity: 15,
      ),
      Exercise(
        name: 'Giros de muñeca',
        description: 'Rota las muñecas en ambas direcciones',
        images: [],
        time: 30,
      ),
      Exercise(
        name: 'Sentadilla en silla',
        description: 'Levántate y siéntate sin usar las manos',
        images: [],
        quantity: 15,
      ),
      Exercise(
        name: 'Elevación de talones sentado',
        description: 'Eleva los talones mientras estás sentado',
        images: [],
        quantity: 20,
      ),
      Exercise(
        name: 'Extensión de espalda',
        description: 'Arquea la espalda hacia atrás en la silla',
        images: [],
        time: 20,
      ),
      Exercise(
        name: 'Estiramiento de cadera',
        description: 'Cruza una pierna sobre la otra y rota',
        images: [],
        time: 30,
      ),
      Exercise(
        name: 'Respiración profunda',
        description: 'Inhala 4 seg, sostén 4 seg, exhala 4 seg',
        images: [],
        quantity: 5,
      ),
    ],
    icon: FontAwesomeIcons.briefcase,
  ),
  Fitness(
    name: 'Entrenamiento para Corredores',
    description: 'Fortalece músculos clave para mejorar tu carrera.',
    difficulty: 'Intermedio',
    tags: ['Running', 'Piernas', 'Core'],
    sets: 2,
    rest: 30,
    gradients: [
      Colors.lightGreen,
      Colors.green,
    ],
    exercises: [
      Exercise(
        name: 'Skipping alto',
        description: 'Corre elevando las rodillas lo más alto posible',
        images: [],
        time: 30,
      ),
      Exercise(
        name: 'Talones a glúteos',
        description: 'Corre llevando los talones a los glúteos',
        images: [],
        time: 30,
      ),
      Exercise(
        name: 'Zancadas caminando',
        description: 'Avanza dando zancadas largas',
        images: [],
        quantity: 20,
      ),
      Exercise(
        name: 'Sentadilla una pierna',
        description: 'Sentadilla bajando lo más posible con una pierna',
        images: [],
        quantity: 8,
      ),
      Exercise(
        name: 'Puente de glúteo una pierna',
        description: 'Puente elevando una pierna al aire',
        images: [],
        quantity: 12,
      ),
      Exercise(
        name: 'Plancha con elevación de pierna',
        description: 'En plancha, eleva una pierna sin mover la cadera',
        images: [],
        quantity: 12,
      ),
      Exercise(
        name: 'Saltos de tijera',
        description: 'Alterna piernas en el aire como tijeras',
        images: [],
        quantity: 20,
      ),
    ],
    icon: FontAwesomeIcons.personRunning,
  ),
  Fitness(
    name: 'Rutina de Movilidad',
    description: 'Mejora el rango de movimiento de tus articulaciones.',
    difficulty: 'Facil',
    tags: ['Movilidad', 'Articulaciones', 'Calentamiento'],
    sets: 1,
    rest: 5,
    gradients: [
      Colors.teal,
      Colors.cyan,
    ],
    exercises: [
      Exercise(
        name: 'Círculos de cadera',
        description: 'Rota las caderas en círculos amplios',
        images: [],
        quantity: 10,
      ),
      Exercise(
        name: 'Molinos de viento',
        description: 'Brazos extendidos, toca pie opuesto alternando',
        images: [],
        quantity: 10,
      ),
      Exercise(
        name: 'Estocada con rotación',
        description: 'En zancada, gira el torso hacia la pierna adelantada',
        images: [],
        quantity: 8,
      ),
      Exercise(
        name: '90/90 de cadera',
        description: 'Sentado, rota las caderas manteniendo las rodillas a 90°',
        images: [],
        quantity: 10,
      ),
      Exercise(
        name: 'Dislocaciones de hombro',
        description: 'Con banda o toalla, pasa de frente a atrás',
        images: [],
        quantity: 10,
      ),
      Exercise(
        name: 'Sentadilla profunda',
        description: 'Baja en sentadilla profunda y mantén',
        images: [],
        time: 60,
      ),
      Exercise(
        name: 'Gato-vaca',
        description: 'Alterna arquear y redondear la columna',
        images: [],
        quantity: 10,
      ),
    ],
    icon: FontAwesomeIcons.person,
  ),
  Fitness(
    name: 'Desafío 7 Minutos',
    description: 'Entrenamiento científico de alta intensidad en 7 minutos.',
    difficulty: 'Intermedio',
    tags: ['Rápido', 'HIIT', 'Científico'],
    sets: 1,
    rest: 10,
    gradients: [
      Colors.deepPurple,
      Colors.purple,
    ],
    exercises: [
      Exercise(
        name: 'Jumping Jacks',
        description: 'Saltos abriendo brazos y piernas',
        images: [],
        time: 30,
      ),
      Exercise(
        name: 'Sentadilla en pared',
        description: 'Mantén posición sentado contra la pared',
        images: [],
        time: 30,
      ),
      Exercise(
        name: 'Lagartijas',
        description: 'Flexiones de brazos clásicas',
        images: [],
        time: 30,
      ),
      Exercise(
        name: 'Abdominales',
        description: 'Crunches básicos',
        images: [],
        time: 30,
      ),
      Exercise(
        name: 'Step-ups',
        description: 'Sube y baja de una silla o escalón',
        images: [],
        time: 30,
      ),
      Exercise(
        name: 'Sentadillas',
        description: 'Sentadillas clásicas',
        images: [],
        time: 30,
      ),
      Exercise(
        name: 'Fondos en silla',
        description: 'Dips apoyando manos en una silla',
        images: [],
        time: 30,
      ),
      Exercise(
        name: 'Plancha',
        description: 'Mantén posición de plancha',
        images: [],
        time: 30,
      ),
      Exercise(
        name: 'Rodillas altas',
        description: 'Corre en el lugar levantando rodillas',
        images: [],
        time: 30,
      ),
      Exercise(
        name: 'Desplantes',
        description: 'Zancadas alternando piernas',
        images: [],
        time: 30,
      ),
      Exercise(
        name: 'Lagartija con rotación',
        description: 'Lagartija abriendo un brazo arriba',
        images: [],
        time: 30,
      ),
      Exercise(
        name: 'Plancha lateral',
        description: 'Mantén posición de lado',
        images: [],
        time: 30,
      ),
    ],
    icon: FontAwesomeIcons.stopwatch,
  ),
];

// Lista de categorías de ejercicios
final fitnessCategories = [
  {
    'name': 'Para Principiantes',
    'icon': FontAwesomeIcons.seedling,
    'color': Colors.green,
    'description': 'Rutinas suaves para comenzar tu camino fitness',
  },
  {
    'name': 'Cardio',
    'icon': FontAwesomeIcons.heartPulse,
    'color': Colors.red,
    'description': 'Ejercicios para fortalecer tu corazón',
  },
  {
    'name': 'Fuerza',
    'icon': FontAwesomeIcons.dumbbell,
    'color': Colors.purple,
    'description': 'Desarrolla músculo y potencia',
  },
  {
    'name': 'Core',
    'icon': FontAwesomeIcons.shieldHalved,
    'color': Colors.amber,
    'description': 'Fortalece tu centro y mejora tu postura',
  },
  {
    'name': 'Flexibilidad',
    'icon': FontAwesomeIcons.spa,
    'color': Colors.cyan,
    'description': 'Mejora tu rango de movimiento',
  },
  {
    'name': 'HIIT',
    'icon': FontAwesomeIcons.bolt,
    'color': Colors.orange,
    'description': 'Alta intensidad para máximos resultados',
  },
];

// Tips de fitness
final fitnessTips = [
  {
    'title': 'Hidratación',
    'tip':
        'Bebe agua antes, durante y después del ejercicio. Al menos 500ml antes de entrenar.',
    'icon': FontAwesomeIcons.droplet,
  },
  {
    'title': 'Calentamiento',
    'tip':
        'Siempre calienta 5-10 minutos antes de ejercitarte para prevenir lesiones.',
    'icon': FontAwesomeIcons.fire,
  },
  {
    'title': 'Descanso',
    'tip':
        'Tus músculos crecen durante el descanso. Duerme 7-8 horas y descansa entre entrenamientos.',
    'icon': FontAwesomeIcons.bed,
  },
  {
    'title': 'Progresión',
    'tip':
        'Aumenta la intensidad gradualmente. Incrementos del 10% semanal son ideales.',
    'icon': FontAwesomeIcons.chartLine,
  },
  {
    'title': 'Respiración',
    'tip':
        'Exhala en el esfuerzo, inhala en el regreso. Nunca contengas la respiración.',
    'icon': FontAwesomeIcons.wind,
  },
  {
    'title': 'Postura',
    'tip':
        'Mantén el core activado y la espalda recta en todos los ejercicios.',
    'icon': FontAwesomeIcons.personArrowUpFromLine,
  },
  {
    'title': 'Consistencia',
    'tip':
        'Es mejor entrenar 3 veces por semana consistentemente que 7 días una semana y ninguno la siguiente.',
    'icon': FontAwesomeIcons.calendarCheck,
  },
  {
    'title': 'Alimentación',
    'tip':
        'Come proteína dentro de los 30 minutos después de entrenar para mejor recuperación.',
    'icon': FontAwesomeIcons.utensils,
  },
];
